"""Technical indicator chart functions using plotly.graph_objects.

Migrated from legacy stock_charts.py. Provides charts for volume flow,
volatility bands, momentum/strength indicators, and options analysis.
All methods use the 'ta' DataFrame from the cfg dict which contains
columns generated by the `ta` (technical analysis) library.
"""

import json

import plotly.graph_objects as go


def _build_line_chart(df, traces, title, x_source="index"):
    """Build a multi-line plotly figure from a DataFrame.

    Args:
        df: Source DataFrame.
        traces: List of (column_name, display_name) tuples.
        title: Chart title string.
        x_source: 'index' to use df.index, or a column name.

    Returns:
        A plotly Figure object.
    """
    fig = go.Figure()
    x_data = df.index.tolist() if x_source == "index" else df[x_source]

    for col, name in traces:
        if col in df.columns:
            fig.add_trace(
                go.Scatter(x=x_data, y=df[col], mode="lines", name=name)
            )

    fig.update_layout(
        title=title, xaxis_title="Date", yaxis_title="Value"
    )
    return fig


class TechnicalCharts:
    """Technical analysis indicator charts."""

    @staticmethod
    def create_cfm_chart(cfg):
        """Chaikin Money Flow line chart.

        Args:
            cfg: Dict with 'ta' (DataFrame with volume_cmf column)
                 and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [("volume_cmf", "Chaikin Money Flow")],
            f"Money Flow : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_eom_chart(cfg):
        """Ease of Movement with SMA line chart.

        Args:
            cfg: Dict with 'ta' (DataFrame with volume_em, volume_sma_em)
                 and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [
                ("volume_em", "Ease of Movement (EoM)"),
                ("volume_sma_em", "EoM SMA."),
            ],
            f"Ease of Movement : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_wt_price_chart(cfg):
        """Volume-weighted average price line chart.

        Args:
            cfg: Dict with 'ta' (DataFrame with volume_vwap column)
                 and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [("volume_vwap", "Vol. Wt. Avg Price")],
            f"Weighted Price Volume : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_volatility_chart(cfg):
        """All volatility indicators combined chart.

        Includes Bollinger %B, high/low band indicators, Keltner channel,
        Donchian channel width, and Ulcer Index.

        Args:
            cfg: Dict with 'ta' (DataFrame with volatility_* columns)
                 and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [
                ("volatility_bbp", "Bollinger (Boll.) % Width"),
                ("volatility_bbhi", "Boll Highband Ind."),
                ("volatility_bbli", "Boll Lowband Ind."),
                ("volatility_kcp", "Keltner ATR Channel (KC) % Width"),
                ("volatility_kchi", "KC Highband Ind."),
                ("volatility_kcli", "KC Lowband Ind."),
                ("volatility_dcp", "Doncian Channel % Width"),
                ("volatility_ui", "Ulcer Index"),
            ],
            f"Stock : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_volatility_width_chart(cfg):
        """Volatility width comparison: Bollinger, Keltner, Donchian.

        Args:
            cfg: Dict with 'ta' (DataFrame with volatility_bbp,
                 volatility_kcp, volatility_dcp) and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [
                ("volatility_bbp", "Bollinger (Boll.) % Width"),
                ("volatility_kcp", "Keltner ATR Channel (KC) % Width"),
                ("volatility_dcp", "Doncian Channel % Width"),
            ],
            f"Volatility Width : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_volatility_high_low_band_chart(cfg):
        """High/low band indicators for Bollinger and Keltner channels.

        Args:
            cfg: Dict with 'ta' (DataFrame with volatility_bbhi,
                 volatility_bbli, volatility_kchi, volatility_kcli)
                 and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [
                ("volatility_bbhi", "Boll Highband Ind."),
                ("volatility_bbli", "Boll Lowband Ind."),
                ("volatility_kchi", "KC Highband Ind."),
                ("volatility_kcli", "KC Lowband Ind."),
            ],
            f"Volatility Hi-Low Bands : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_ulcer_chart(cfg):
        """Ulcer Index line chart.

        Args:
            cfg: Dict with 'ta' (DataFrame with volatility_ui column)
                 and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [("volatility_ui", "Ulcer Index")],
            f"Ulcer Index : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_strength_all_chart(cfg):
        """All momentum/strength indicators combined chart.

        Includes RSI, StochRSI, TSI, Ultimate Oscillator, Williams %R,
        Awesome Oscillator, and ROC.

        Args:
            cfg: Dict with 'ta' (DataFrame with momentum_* columns)
                 and 'ticker' (str).

        Returns:
            JSON string of the plotly figure dict.
        """
        df = cfg.get("ta", None)
        ticker = cfg["ticker"]

        fig = _build_line_chart(
            df,
            [
                ("momentum_rsi", "RSIIndicator"),
                ("momentum_stoch_rsi", "StochRSIIndicator"),
                ("momentum_tsi", "TSIIndicator"),
                ("momentum_uo", "UltimateOscillator"),
                ("momentum_wr", "WilliamsRIndicator"),
                ("momentum_ao", "AwesomeOscillatorIndicator"),
                ("momentum_roc", "ROCIndicator"),
            ],
            f"Stock : {ticker}",
        )
        return json.dumps(fig.to_dict())

    @staticmethod
    def create_call_analysis_chart(cfg):
        """Options call analysis grouped bar chart.

        Groups bars by strike price with expiration date on x-axis.

        Args:
            cfg: Dict with 'ticker', 'df_call_analysis' (DataFrame with
                 expirationDate, effectiveValuePerShare, strike, Tooltip).

        Returns:
            JSON string of the plotly figure dict.
        """
        ticker = cfg["ticker"]
        df = cfg["df_call_analysis"]

        fig = go.Figure()
        if len(df) > 0 and "strike" in df.columns:
            for strike_val, group in df.groupby("strike"):
                fig.add_trace(
                    go.Bar(
                        x=group["expirationDate"],
                        y=group["effectiveValuePerShare"],
                        name=str(strike_val),
                        text=group.get("Tooltip", None),
                    )
                )
        elif len(df) > 0:
            fig.add_trace(
                go.Bar(
                    x=df["expirationDate"],
                    y=df["effectiveValuePerShare"],
                    name="Share Holding Ratio",
                    text=df.get("Tooltip", None),
                )
            )

        fig.update_layout(
            title=f"Share Holding Ratio : {ticker}",
            xaxis=dict(type="category", tickangle=-45),
            barmode="group",
        )
        return json.dumps(fig.to_dict())
